# Generated by Django 3.0.1 on 2020-03-31 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Lampe', 'Lampe'), ('Prise', 'Prise'), ('Rideau', 'Rideau')], max_length=255)),
                ('commande', models.CharField(max_length=255)),
                ('commande2', models.CharField(blank=True, max_length=255, null=True)),
                ('commande3', models.CharField(blank=True, max_length=255, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to='chambres.Chambre')),
                ('user', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
