# Generated by Django 3.0.1 on 2020-03-31 23:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('local_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together={('local_id', 'user')},
        ),
    ]
