# Generated by Django 3.0.1 on 2020-04-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambres', '0002_auto_20200401_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('local_id', models.PositiveIntegerField()),
                ('commande', models.PositiveIntegerField()),
                ('off_all', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
