# Generated by Django 3.0.1 on 2020-03-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191014_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fax',
        ),
    ]
